### ISSUE TITLE
Adding depth to the to_pb to constraint recursively convert relation

### ISSUE THREAD

**Issue by cecilulysess** [myyang/django-pb-model#19]
Currently the logic recursively convert all relations. This will be undesirable in many cases.

How about change ProtoBufMixin's to_pb method from

`def to_pb(self):`

to 

`def to_pb(self, depth=None):`

for example depth = 0 does not convert any relation,
depth = 1 convert only direct relation
etc.

Does this make sense? Happy to PR if owner agree on this feature.

**Comment by myyang** [comment]
great, but considering backward compatibility what value would be the default value ?

**Comment by myyang** [comment]
Oops, I missed None. So None would be the original flow, right?

**Comment by cecilulysess** [comment]
Yes

**Comment by myyang** [comment]
link #20
