### ISSUE TITLE
JSON filed in protobuff message

### ISSUE THREAD

**Issue by maruthi8** [myyang/django-pb-model#2]
`class ChoiceQuestionModel(models.Model):

    answer_choices = JSONField(null=True, blank=True)  # required
    expected_correct_answers_count = models.PositiveIntegerField(default=0)`

How can i write message for JSONField or i how can i include jsonfield in protobuff message?

**Comment by myyang** [comment]
Please see [README](https://github.com/myyang/django-pb-model#custom-fields), you may need some implementation by yourself. 😸
