### ISSUE TITLE
Readme lists support for Django 1.11 but setup.py specifies 'django>=1.8,<1.11',

### ISSUE THREAD

**Issue by dhendry** [myyang/django-pb-model#4]
- https://github.com/myyang/django-pb-model#compatibility
- https://github.com/myyang/django-pb-model/blob/master/setup.py#L29

Does this project support django 1.11 or not? I hope so, it looks cool :)

**Comment by myyang** [comment]
Oops. 
Project is tested with Django1.11 on Travis ( see: https://github.com/myyang/django-pb-model/blob/master/.travis.yml) 

Let me update the `setup.py`.
Thanks!

**Comment by myyang** [comment]
Updated to v0.1.6.

Thanks again!
